# Generated by Django 4.0.3 on 2022-04-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categorie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='post_category',
        ),
    ]
