# Generated by Django 4.0.1 on 2022-04-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_category_post_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='qoute',
            field=models.CharField(default='', max_length=300),
        ),
    ]
