# Generated by Django 4.0.3 on 2022-04-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_parent_comment_parent_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.comment'),
        ),
    ]
